### ISSUE TITLE
通过web端 函数无法正常运行

### ISSUE THREAD

**Issue by future-death** [jiemo9527/FDM#1]
环境：centos7.6  Python2.7  php7.2  ffmpeg  aria2  yt-dlp

$cat /usr/share/nginx/html/test.php
# <?php
# $a="https://b.baobuzz.com/ipfs/559078.m3u8?sign=3ab3d41d7e1659947b4a013d8553b847";
# $b="x.mp4";
# $c="1";
# $cmd='python fDM.py '. $a . ' ' . $b . ' ' . $c;
# system($cmd);
# ?>

$php test.php       能够正常执行下载

如果通过webui传入参数，会立刻显示下载成功，但并没有在后台执行下载任务

小白一个，没有调试思路，大佬有什么建议吗 多谢指教

**Comment by jiemo9527** [comment]
我使用你的链接和文件名是可以正常下载的，请检查文件夹目录是否存在，目录是否开放写入权限。
也可以在控制台手动输入下命令查看错误信息

**Comment by jiemo9527** [comment]
![QQ截图20220910001002](https://user-images.githubusercontent.com/36528975/189394400-3088ce51-4c64-40fe-aa28-d224bed86648.png)

**Comment by future-death** [comment]
权限全开
![x](https://user-images.githubusercontent.com/62785542/189410532-e3548dce-fbb7-4bd7-a695-db0416ffc5ca.png)
先前已更改目录
![y](https://user-images.githubusercontent.com/62785542/189410549-34b38d4c-d808-4172-a47d-c8edde0a0ef9.png)
![z](https://user-images.githubusercontent.com/62785542/189410565-d92cf3b0-c6a1-4720-b83c-54cff97a42fd.png)
问题依旧。控制台还不会用~
暂时先这样吧，多谢  这种项目我只找到你这一个诶

**Comment by future-death** [comment]
问题应该是nginx用户无法调用ffmpeg命令
